"""
Regression test: behavior model pickle must be loadable from any import context.

The failure mode: if the model is saved while behavior_model.py runs as __main__,
BehaviorModel is pickled as "__main__.BehaviorModel". Loading it from Streamlit,
pytest, or python -c raises:
    AttributeError: Can't get attribute 'BehaviorModel' on <module '__main__' ...>

This test catches that by unpickling from a normal imported module and calling
analyze_behavior end-to-end. It will fail if the .pkl is ever regenerated by
running behavior_model.py directly as a script.
"""

import pickle
import pytest
from shared.schemas import SessionContext


def test_behavior_model_pickle_module_path():
    """BehaviorModel class must be stored under its real module path, not __main__."""
    with open("models/behavior_model/behavior_model.pkl", "rb") as f:
        model = pickle.load(f)

    module = type(model).__module__
    assert module == "features.behavior.behavior_model", (
        f"BehaviorModel was pickled as '{module}.BehaviorModel'. "
        f"It must be 'features.behavior.behavior_model.BehaviorModel'. "
        f"Regenerate the pickle by running:\n"
        f"  python3 -c \"from features.behavior.behavior_model import train_and_save; train_and_save()\""
    )


def test_analyze_behavior_callable_from_imported_module():
    """analyze_behavior must not raise when called from any import context."""
    from features.prediction import analyze_behavior

    ctx = SessionContext(
        session_id="S000001",
        operator_id="OP1001",
        machine_id="EXC001",
    )
    result = analyze_behavior(ctx)

    assert result is not None
    assert result.session_id == "S000001"
    assert result.attribution in (
        "operator-driven", "context-driven", "mixed", "insufficient_evidence"
    )
    assert 0.0 <= result.confidence <= 1.0
    assert isinstance(result.coaching_eligible, bool)
    assert result.synthetic_flag is True


def test_context_share_zero_gap_suppresses_coaching():
    """Zero residual must return context_share=1.0, not 0.0 (D040)."""
    from shared.schemas import BehaviorResult

    zero = BehaviorResult(
        session_id="S_ZERO",
        attribution="insufficient_evidence",
        confidence=0.0,
        observed_value=0.12,
        expected_value=0.12,
        operator_residual=0.0,
        context_explained_component=0.0,
        coaching_eligible=False,
        synthetic_flag=True,
    )
    assert zero.context_share() == 1.0, (
        "context_share() returned 0.0 for a zero-gap result. "
        "This would pass the training gate and coach an operator who deviated by nothing."
    )
